#!/bin/sh

function pause(){
  read -p "$*"
}

cp samples/VerySimpleMinus.rb /tmp/VerySimple.rb

echo "$ ruby bin/cli.rb -C -f samples/VerySimple.rb -g /tmp/VerySimple.rb"

pause

ruby bin/cli.rb -C -f samples/VerySimple.rb -g /tmp/VerySimple.rb
