#!/bin/sh

function pause(){
  read -p "$*"
}

cp samples/VerySimpleMinus.rb /tmp/VerySimple.rb

vim +sp\ samples/VerySimple.rb /tmp/VerySimple.rb

clear

ruby bin/cli.rb -h

pause

echo "$ ruby bin/cli.rb -G -f samples/VerySimple.rb"

pause

ruby bin/cli.rb -G -f samples/VerySimple.rb

pause Continue...

vim +"normal gg=G" +w tests/test_VerySimple.rb

vim +3s/VerySimple/VerySimpleMinus +wq tests/test_VerySimple.rb

mv tests/test_VerySimple.rb samples

echo "$ ruby samples/test_VerySimple.rb"

pause

ruby samples/test_VerySimple.rb

pause

clear

echo "$ ruby bin/cli.rb -C -f samples/VerySimple.rb -g /tmp/VerySimple.rb"

pause

ruby bin/cli.rb -C -f samples/VerySimple.rb -g /tmp/VerySimple.rb
